### ISSUE TITLE
Panic when calling "getReader" on a "Response.body" object

### ISSUE THREAD

**Issue by johanbrandhorst** [neelance/go#10]
I've been playing around with the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) using the new Callbacks, and I ran into the following unexpected panic:

```bash
panic: JavaScript error: `target` argument of Reflect.get must be an object, got (void 0) wasm_exec.js:59:6
wasm_exec.js:59:6
goroutine 6 [running]: wasm_exec.js:59:6
syscall/js.Value.Call(0x0, 0x1e8e7, 0x9, 0x0, 0x0, 0x0, 0xc01e058) wasm_exec.js:59:6
	$GOPATH/src/github.com/neelance/go/src/syscall/js/js.go:143 +0x7 wasm_exec.js:59:6
main.main.func1(0xc01e058, 0x1, 0x1) wasm_exec.js:59:6
	$GOPATH/src/github.com/johanbrandhorst/wasm-experiments/bug/main.go:15 +0x4 wasm_exec.js:59:6
syscall/js/callback.callbackLoop() wasm_exec.js:59:6
	$GOPATH/src/github.com/neelance/go/src/syscall/js/callback/callback.go:77 +0x8 wasm_exec.js:59:6
created by syscall/js/callback.init.0 wasm_exec.js:59:6
	$GOPATH/src/github.com/neelance/go/src/syscall/js/callback/callback.go:50 +0x2 wasm_exec.js:59:6
exit code: 2 wasm_exec.js:47:6 
```
I've written a minimal example that reproduces the issue:
```go
// +build js,wasm

package main

import (
	"syscall/js"
	"syscall/js/callback"
)

func main() {
	wait := make(chan struct{})
	promise := js.Global.Call("fetch", "https://api.github.com")
	promise.Call("then", callback.New(func(args []js.Value) {
		response := args[0]
		r := response.Get("body").Call("getReader") // <-- Panic here
		r.Call("read")
		close(wait)
	}).Value)
	<-wait
}
```

This is happening for me on Firefox 61b4.

**Comment by shurcooL** [comment]
Did you check if the same functionality in JavaScript works?

Does that version of Firefox support streams API by now? https://caniuse.com/#search=ReadableStream Last time I checked (some time ago), it didn’t. Have you tried it in Chrome or other browsers?

`Call` is documented to panic if the method doesn’t exist. Can you try checking it’s not the case?

```diff
 b := response.Get("body")
+if b == js.Undefined || b == js.Null {
+    // handle no body
+}
+if gr := b.Get("getReader"); gr == js.Undefined || gr == js.Null {
+    // handle no getReader
+}
 r := b.Call("getReader")
```

**Comment by shurcooL** [comment]
Yeah, just checked latest Firefox Nightly, and Streams API is simply not supported (with default settings). Compare Firefox Nightly (62.0a1):

![image](https://user-images.githubusercontent.com/1924134/39963012-f6fa0ca8-562d-11e8-92eb-93d1012ce510.png)

Versus stable Chrome (66.0.3359.139):

![image](https://user-images.githubusercontent.com/1924134/39963021-27cbe996-562e-11e8-9ffe-003b25be2058.png)

**Comment by johanbrandhorst** [comment]
@shurcooL ah of course! Can't believe I didn't think of that. Good thinking again!

**Comment by johanbrandhorst** [comment]
I'll leave this open for @neelance to decide whether something should or should not be done.

**Comment by johanbrandhorst** [comment]
For other Firefox users; I turned this on by toggling `dom.streams.enabled` and `javascript.options.streams prefs` in `about:config`.
