### ISSUE TITLE
Panic when Context timeout expires

### ISSUE THREAD

**Issue by johanbrandhorst** [neelance/go#11]
Not sure this is documented already, but when using a context with a timeout it triggers a panic on expiry. This code triggers the error:

```go
// +build js,wasm

package main

import (
	"context"
	"fmt"
	"time"
)

func main() {
	ctx, _ := context.WithTimeout(context.Background(), time.Second)

	select {
	case <-ctx.Done(): // <-- Panic here
		fmt.Println("Context timed out")
	}
	fmt.Println("done")
}
```

Traceback:

```bash
fatal error: notetsleepg not supported by js

goroutine 6 [running]:
runtime.throw(0x32ecc, 0x1f)
	$GOPATH/src/github.com/neelance/go/src/runtime/panic.go:589 +0x6 fp=0xc026f50 sp=0xc026f28 pc=0x11a00006
runtime.notetsleepg(0x135c20, 0x3b8b8800, 0x0)
	$GOPATH/src/github.com/neelance/go/src/runtime/lock_js.go:62 +0x2 fp=0xc026f68 sp=0xc026f50 pc=0x108d0002
runtime.timerproc(0x135c00)
	$GOPATH/src/github.com/neelance/go/src/runtime/time.go:261 +0x2d fp=0xc026fd8 sp=0xc026f68 pc=0x12a8002d
runtime.goexit()
	$GOPATH/src/github.com/neelance/go/src/runtime/asm_wasm.s:425 +0x1 fp=0xc026fe0 sp=0xc026fd8 pc=0x13620001
created by runtime.(*timersBucket).addtimerLocked
	$GOPATH/src/github.com/neelance/go/src/runtime/time.go:160 +0x11

goroutine 1 [chan receive]:
main.main()
	$GOPATH/src/github.com/johanbrandhorst/wasm-experiments/timeout/main.go:15 +0x8

goroutine 4 [runnable]:
syscall/js.callbackLoop()
	$GOPATH/src/github.com/neelance/go/src/syscall/js/callback.go:46
created by syscall/js.init.0
	$GOPATH/src/github.com/neelance/go/src/syscall/js/callback.go:43 +0x2
exit code: 2
```

Triggered by https://github.com/neelance/go/blob/master/src/runtime/lock_js.go#L54. I assume since this isn't already implemented it's non-trivial to implement, but we should keep track of this in this issue.

**Comment by neelance** [comment]
This is due to the latest commit being WIP. The `time` package is currently broken.

**Comment by johanbrandhorst** [comment]
Ugh I even remembered reading that in your last comment. Sorry!

**Comment by neelance** [comment]
The `time` package is now working fine again.
