### ISSUE TITLE
buildof golang failing for me

### ISSUE THREAD

**Issue by gedw99** [neelance/go#21]
i have golang installed via homebrew.
I try to install the wasm-wip using the all.bash and it blows up when runnign a tcp test.
I have never compile hte golang source and so i bet i am doing something lame ?

env:
````
x-MacBook-Pro:golang-bootstrap apple$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apple/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build310209814=/tmp/go-build -gno-record-gcc-switches -fno-common"
````

the output:

````

x-MacBook-Pro:golang-bootstrap apple$ make build
cd /Users/apple/goroots/wasm-wip && git checkout wasm-wip
Already on 'wasm-wip'
Your branch is up to date with 'origin/wasm-wip'.
cd /Users/apple/goroots/wasm-wip/src && ./all.bash
Building Go cmd/dist using /usr/local/Cellar/go/1.10.2/libexec.
Building Go toolchain1 using /usr/local/Cellar/go/1.10.2/libexec.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.

##### Testing packages.
ok      archive/tar     0.073s
ok      archive/zip     3.711s
ok      bufio   0.074s
ok      bytes   0.390s
ok      compress/bzip2  0.096s
ok      compress/flate  1.159s
ok      compress/gzip   0.031s
ok      compress/lzw    0.021s
ok      compress/zlib   0.029s
ok      container/heap  0.020s
ok      container/list  0.018s
ok      container/ring  0.024s
ok      context 1.012s
ok      crypto  0.014s
ok      crypto/aes      0.040s
ok      crypto/cipher   0.036s
ok      crypto/des      0.021s
ok      crypto/dsa      0.016s
ok      crypto/ecdsa    0.179s
ok      crypto/elliptic 0.035s
ok      crypto/hmac     0.012s
ok      crypto/md5      0.016s
ok      crypto/rand     0.073s
ok      crypto/rc4      0.127s
ok      crypto/rsa      0.087s
ok      crypto/sha1     0.038s
ok      crypto/sha256   0.022s
ok      crypto/sha512   0.018s
ok      crypto/subtle   0.015s
ok      crypto/tls      1.034s
ok      crypto/x509     2.216s
ok      database/sql    0.584s
ok      database/sql/driver     0.012s
ok      debug/dwarf     0.033s
ok      debug/elf       0.038s
ok      debug/gosym     0.268s
ok      debug/macho     0.018s
ok      debug/pe        0.023s
ok      debug/plan9obj  0.017s
ok      encoding/ascii85        0.017s
ok      encoding/asn1   0.015s
ok      encoding/base32 0.028s
ok      encoding/base64 0.017s
ok      encoding/binary 0.018s
ok      encoding/csv    0.017s
ok      encoding/gob    0.046s
ok      encoding/hex    0.018s
ok      encoding/json   0.695s
ok      encoding/pem    0.041s
ok      encoding/xml    0.029s
ok      errors  0.011s
ok      expvar  0.034s
ok      flag    0.010s
ok      fmt     0.120s
ok      go/ast  0.013s
ok      go/build        0.421s
ok      go/constant     0.010s
ok      go/doc  0.089s
ok      go/format       0.018s
ok      go/importer     0.140s
ok      go/internal/gccgoimporter       0.017s
ok      go/internal/gcimporter  0.458s
ok      go/internal/srcimporter 2.002s
ok      go/parser       0.035s
ok      go/printer      0.484s
ok      go/scanner      0.012s
ok      go/token        0.040s
ok      go/types        1.279s
ok      hash    0.011s
ok      hash/adler32    0.016s
ok      hash/crc32      0.020s
ok      hash/crc64      0.011s
ok      hash/fnv        0.010s
ok      html    0.014s
ok      html/template   0.050s
ok      image   0.124s
ok      image/color     0.032s
ok      image/draw      0.073s
ok      image/gif       0.413s
ok      image/jpeg      0.566s
ok      image/png       0.046s
ok      index/suffixarray       0.023s
ok      internal/cpu    0.010s
ok      internal/poll   0.020s
ok      internal/singleflight   0.023s
ok      internal/trace  2.896s
ok      io      0.041s
ok      io/ioutil       0.019s
ok      log     0.012s
ok      log/syslog      1.256s
ok      math    0.015s
ok      math/big        2.826s
ok      math/bits       0.017s
ok      math/cmplx      0.018s
ok      math/rand       0.365s
ok      mime    0.014s
ok      mime/multipart  0.565s
ok      mime/quotedprintable    0.114s
--- FAIL: TestFileConn (0.00s)
        file_test.go:115: file file+net tcp:127.0.0.1:52753->127.0.0.1:52752: protocol not available
--- FAIL: TestFileListener (0.00s)
        file_test.go:191: file file+net tcp4:127.0.0.1:52754->: protocol not available
--- FAIL: TestFilePacketConn (0.00s)
        file_test.go:281: file file+net udp4:127.0.0.1:65499->: protocol not available
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e9b89]

goroutine 803 [running]:
testing.tRunner.func1(0xc000156a00)
        /Users/apple/goroots/wasm-wip/src/testing/testing.go:792 +0x387
panic(0x1247160, 0x14433f0)
        /Users/apple/goroots/wasm-wip/src/runtime/panic.go:494 +0x1b9
net.TestUnixUnlink.func5(0xc000156a00)
        /Users/apple/goroots/wasm-wip/src/net/unixsock_test.go:408 +0xc9
testing.tRunner(0xc000156a00, 0xc0001465c0)
        /Users/apple/goroots/wasm-wip/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
        /Users/apple/goroots/wasm-wip/src/testing/testing.go:878 +0x353
FAIL    net     1.533s
ok      net/http        4.598s
ok      net/http/cgi    0.841s
ok      net/http/cookiejar      0.032s
ok      net/http/fcgi   0.028s
ok      net/http/httptest       0.042s
ok      net/http/httptrace      0.022s
ok      net/http/httputil       0.081s
ok      net/http/internal       0.011s
ok      net/http/pprof  2.044s
ok      net/internal/socktest   0.010s
ok      net/mail        0.010s
ok      net/rpc 0.047s
ok      net/rpc/jsonrpc 0.051s
ok      net/smtp        0.054s
ok      net/textproto   0.012s
ok      net/url 0.026s
ok      os      0.735s
--- FAIL: TestExtraFiles (0.00s)
        exec_test.go:428: TestExtraFiles: Something already leaked - closed fd 23
        exec_test.go:428: TestExtraFiles: Something already leaked - closed fd 24
        exec_test.go:428: TestExtraFiles: Something already leaked - closed fd 25
        exec_test.go:567: file file+net tcp:127.0.0.1:54014->: protocol not available
--- FAIL: TestExtraFilesRace (0.31s)
        exec_test.go:653: iteration 0, process A got:

                want:
                fd3: listener 127.0.0.1:54015

        exec_test.go:656: iteration 0, process B got:

                want:
                fd3: listener 127.0.0.1:54016

        exec_test.go:653: iteration 1, process A got:

                want:
                fd3: listener 127.0.0.1:54017

        exec_test.go:656: iteration 1, process B got:

                want:
                fd3: listener 127.0.0.1:54018

        exec_test.go:653: iteration 2, process A got:

                want:
                fd3: listener 127.0.0.1:54019

        exec_test.go:656: iteration 2, process B got:

                want:
                fd3: listener 127.0.0.1:54020

        exec_test.go:653: iteration 3, process A got:

                want:
                fd3: listener 127.0.0.1:54021

        exec_test.go:656: iteration 3, process B got:

                want:
                fd3: listener 127.0.0.1:54022

        exec_test.go:653: iteration 4, process A got:

                want:
                fd3: listener 127.0.0.1:54023

        exec_test.go:656: iteration 4, process B got:

                want:
                fd3: listener 127.0.0.1:54024

        exec_test.go:653: iteration 5, process A got:

                want:
                fd3: listener 127.0.0.1:54025

        exec_test.go:656: iteration 5, process B got:

                want:
                fd3: listener 127.0.0.1:54026

        exec_test.go:653: iteration 6, process A got:

                want:
                fd3: listener 127.0.0.1:54027

        exec_test.go:656: iteration 6, process B got:

                want:
                fd3: listener 127.0.0.1:54028

        exec_test.go:653: iteration 7, process A got:

                want:
                fd3: listener 127.0.0.1:54029

        exec_test.go:656: iteration 7, process B got:

                want:
                fd3: listener 127.0.0.1:54030

        exec_test.go:653: iteration 8, process A got:

                want:
                fd3: listener 127.0.0.1:54031

        exec_test.go:656: iteration 8, process B got:

                want:
                fd3: listener 127.0.0.1:54032

        exec_test.go:653: iteration 9, process A got:

                want:
                fd3: listener 127.0.0.1:54033

        exec_test.go:656: iteration 9, process B got:

                want:
                fd3: listener 127.0.0.1:54034

FAIL
FAIL    os/exec 1.196s
ok      os/signal       4.763s
ok      os/user 0.015s
ok      path    0.009s
ok      path/filepath   0.055s
ok      reflect 0.442s
ok      regexp  0.123s
ok      regexp/syntax   1.021s
ok      runtime 37.176s
ok      runtime/debug   0.089s
ok      runtime/internal/atomic 0.132s
ok      runtime/internal/sys    0.011s
ok      runtime/pprof   4.392s
ok      runtime/pprof/internal/profile  0.011s
ok      runtime/trace   2.102s
ok      sort    0.205s
ok      strconv 1.632s
ok      strings 0.499s
ok      sync    0.334s
ok      sync/atomic     0.036s
--- FAIL: TestPassFD (0.01s)
        syscall_unix_test.go:162: child process: "failed to find unix fd\n", <nil>
FAIL
FAIL    syscall 0.064s
ok      testing 1.136s
ok      testing/quick   0.230s
ok      text/scanner    0.011s
ok      text/tabwriter  0.014s
ok      text/template   0.718s
ok      text/template/parse     0.015s
ok      time    2.687s
ok      unicode 0.015s
ok      unicode/utf16   0.012s
ok      unicode/utf8    0.019s
ok      vendor/golang_org/x/crypto/chacha20poly1305     0.481s
ok      vendor/golang_org/x/crypto/cryptobyte   0.016s
ok      vendor/golang_org/x/crypto/curve25519   0.032s
ok      vendor/golang_org/x/crypto/internal/chacha20    0.065s
ok      vendor/golang_org/x/crypto/poly1305     0.015s
ok      vendor/golang_org/x/net/dns/dnsmessage  0.106s
ok      vendor/golang_org/x/net/http/httpguts   0.014s
ok      vendor/golang_org/x/net/http2/hpack     0.016s
ok      vendor/golang_org/x/net/idna    0.014s
ok      vendor/golang_org/x/net/nettest 0.775s
ok      vendor/golang_org/x/net/route   0.020s
ok      vendor/golang_org/x/text/transform      0.011s
ok      vendor/golang_org/x/text/unicode/norm   0.011s
ok      cmd/addr2line   2.804s
ok      cmd/api 0.019s
ok      cmd/asm/internal/asm    1.039s
ok      cmd/asm/internal/lex    0.011s
ok      cmd/compile     19.512s
ok      cmd/compile/internal/gc 29.335s
ok      cmd/compile/internal/ssa        0.491s
ok      cmd/compile/internal/syntax     0.023s
ok      cmd/compile/internal/test       0.011s [no tests to run]
ok      cmd/compile/internal/types      0.014s
ok      cmd/cover       2.195s
ok      cmd/doc 0.052s
ok      cmd/fix 8.289s
ok      cmd/go  84.439s
ok      cmd/go/internal/cache   2.274s
ok      cmd/go/internal/generate        0.022s
ok      cmd/go/internal/get     0.037s
ok      cmd/go/internal/load    0.019s
ok      cmd/go/internal/work    0.034s
ok      cmd/gofmt       0.071s
ok      cmd/internal/buildid    0.349s
ok      cmd/internal/dwarf      0.010s
ok      cmd/internal/edit       0.013s
ok      cmd/internal/goobj      1.928s
ok      cmd/internal/obj        0.012s
ok      cmd/internal/obj/arm64  0.062s
ok      cmd/internal/obj/x86    0.430s
ok      cmd/internal/objabi     0.012s
ok      cmd/internal/src        0.012s
ok      cmd/internal/test2json  0.142s
ok      cmd/link        2.990s
ok      cmd/link/internal/ld    11.562s
ok      cmd/nm  6.591s
ok      cmd/objdump     4.097s
ok      cmd/pack        3.315s
ok      cmd/trace       0.048s
ok      cmd/vendor/github.com/google/pprof/internal/binutils    0.044s
ok      cmd/vendor/github.com/google/pprof/internal/driver      0.515s
ok      cmd/vendor/github.com/google/pprof/internal/elfexec     0.012s
ok      cmd/vendor/github.com/google/pprof/internal/graph       0.024s
ok      cmd/vendor/github.com/google/pprof/internal/measurement 0.013s
ok      cmd/vendor/github.com/google/pprof/internal/report      0.053s
ok      cmd/vendor/github.com/google/pprof/internal/symbolizer  0.027s
ok      cmd/vendor/github.com/google/pprof/internal/symbolz     0.035s
ok      cmd/vendor/github.com/google/pprof/profile      0.083s
ok      cmd/vendor/github.com/ianlancetaylor/demangle   0.031s
ok      cmd/vendor/golang.org/x/arch/arm/armasm 0.027s
ok      cmd/vendor/golang.org/x/arch/arm64/arm64asm     0.298s
ok      cmd/vendor/golang.org/x/arch/ppc64/ppc64asm     0.017s
ok      cmd/vendor/golang.org/x/arch/x86/x86asm 0.153s
ok      cmd/vendor/golang.org/x/crypto/ssh/terminal     0.013s
--- FAIL: TestPassFD (0.01s)
        syscall_unix_test.go:159: child process: "failed to find unix fd\n", <nil>
FAIL
FAIL    cmd/vendor/golang.org/x/sys/unix        0.383s
ok      cmd/vet 3.085s
ok      cmd/vet/internal/cfg    0.014s
2018/05/27 23:10:19 Failed: exit status 1
make: *** [build] Error 1
````

**Comment by neelance** [comment]
This is a "work in progress" branch. Please don't expect all tests to always pass.
